const DATETIME_DISPLAY_FORMAT = 'YYYY-MM-DD, HH:mm'
const DATETIME_DISPLAY_FORMAT_BE = 'BBBB-MM-DD, HH:mm'

const DATE_DISPLAY_FORMAT = 'YYYY-MM-DD'
const DATE_DISPLAY_FORMAT_BE = 'BBBB-MM-DD'

const RESULT_HISTORY_DISPLAY = 'MMM DD, YYYY HH:mm:ss'
const RESULT_HISTORY_DISPLAY_BE = 'MMM DD, BBBB HH:mm:ss'

const REPRESENT_DATE_DATA = 'MMM DD, YYYY'
const REPRESENT_DATE_DATA_BE = 'MMM DD, BBBB'

const REPRESENT_DATETIME_DATA = 'MMM DD, YYYY HH:mm'
const REPRESENT_DATETIME_DATA_BE = 'MMM DD, BBBB HH:mm'


export { 
  DATETIME_DISPLAY_FORMAT, DATETIME_DISPLAY_FORMAT_BE, 
  DATE_DISPLAY_FORMAT, DATE_DISPLAY_FORMAT_BE,
  RESULT_HISTORY_DISPLAY, RESULT_HISTORY_DISPLAY_BE,
  REPRESENT_DATE_DATA, REPRESENT_DATE_DATA_BE, 
  REPRESENT_DATETIME_DATA, REPRESENT_DATETIME_DATA_BE
} 